# Generated by Django 3.1.13 on 2021-12-09 15:11

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='articles/%Y/%m/%d')),
                ('title_en', models.CharField(max_length=255, verbose_name='Name (EN)')),
                ('title_de', models.CharField(max_length=255, verbose_name='Name (DE)')),
                ('content_en', models.TextField(verbose_name='Content (EN)')),
                ('content_de', models.TextField(verbose_name='Content (DE)')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-creation_date'],
            },
        ),
    ]
