# Generated by Django 3.1.13 on 2021-12-09 15:29

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_de',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Content (DE)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_en',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Content (EN)'),
        ),
    ]
